SquirrelCorporation/SquirrelServersManager

client/Dockerfile, client/package.json, proxy/Dockerfile, server/Dockerfile, server/package.json, shared-lib/package.json
The version number has been updated in the package.json files for the shared-lib, server, and client services. Additionally, labels have been added to the Dockerfiles to include source information, a brief description, and the license for the Squirrel Servers Manager application for client, server, and proxy services.
=> Update version and Dockerfiles for all services

client/package.json, server/package.json
Both SquirrelServersManager's server and client packages.json files have been updated with the new version, changing from 0.1.2 to 0.1.12.
=> Update server and client versions to 0.1.12

client/src/components/DeviceConfiguration/CheckDeviceConnection.tsx, client/src/components/DeviceConfiguration/DockerConnectionForm.tsx, client/src/components/DeviceConfiguration/SSHConnectionForm.tsx, client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/pages/Admin/Inventory/components/ConfigurationModal.tsx, client/src/pages/Admin/Inventory/components/ConnectionTestTab.tsx, client/src/pages/Admin/Inventory/components/DockerConfigurationForm.tsx, client/src/pages/Admin/Inventory/components/SSHConfigurationForm.tsx, client/src/services/rest/device.ts, server/src/routes/devices.ts, server/src/services/devices/check-connection.ts, server/src/services/devices/check-connection.validator.ts, server/src/services/devices/deviceauth.ts, server/src/services/devices/deviceauth.validator.ts, server/src/use-cases/DeviceUseCases.ts, shared-lib/.gitignore, shared-lib/src/types/api.ts, shared-lib/src/validation/index.ts
Expanded the device authentication validator to include more comprehensive checks. Added a feature to test a device's ansible and docker connection. Sensitive information handling has also been revamped where sensitive fields are now replaced with placeholders when retrieved, and these placeholders can be left in place when updating. Added new UI components to facilitate the usage of these new features.
=> Add device connection check and enhanced credential handling

site/docs/quickstart.md
Fixes: https://github.com/SquirrelCorporation/SquirrelServersManager/issues/34
=> removed extra Char from Docker-compose file

client/package.json, server/package.json, server/src/core/startup/index.ts, shared-lib/package.json
The update involves removing unnecessary import statements from the 'index.ts' file within the server's core startup directory. This contributes to cleaner, more efficient
=> Update version numbers and remove unused imports

client/src/pages/Dashboard/ChartComponents/ChartCard.tsx, client/src/pages/Dashboard/Components/AvailabilityCard.tsx, client/src/pages/Dashboard/Components/MainChartCard.tsx, client/src/pages/Dashboard/Components/ServicesCard.tsx, client/src/pages/Dashboard/Components/SystemPerformanceCard.tsx, client/src/pages/Devices/index.tsx, client/src/pages/Playbooks/components/TreeComponent.tsx
Several improvements have been made to improve user experience and code effectiveness. Loading states have been added to several components to visually indicate to users when data is still loading. This is accompanied by code modifications for a more efficient data fetching process, which now utilizes .finally() to ensure the loading state resets even after an error. Other minor adjustments include a tweak to TerminalStateProps and a slight UI adjustment to the TreeComponent.
=> Add loading states and optimize data fetching

client/src/components/ServiceComponents/ServiceQuickAction/ServiceQuickActionDropDown.tsx, client/src/components/ServiceComponents/ServiceQuickAction/ServiceQuickActionReference.tsx, client/src/pages/Services/index.tsx, client/src/services/rest/containers.ts, server/src/integrations/docker/core/WatcherEngine.ts, server/src/integrations/docker/watchers/providers/docker/Docker.ts, server/src/routes/containers.ts, server/src/services/containers/containers.ts, server/src/services/containers/containers.validator.ts, server/src/services/devices/device.ts, server/src/use-cases/ContainerUseCases.ts, shared-lib/src/enums/container.ts, shared-lib/src/index.ts
The code updates involve adding several container actions (including stop, start, restart, pause, kill), and updates to container watchers. Other minor methods and functions have been adjusted for compatibility with these main updates. Consequently, significant changes have been made across a number of files to accommodate these additions.
=> [FEAT]  Actions on containers

client/src/pages/Services/components/ContainerAvatar.tsx, client/src/pages/Services/index.tsx
The ContainerAvatar logic and component have been extracted from the Services page into a separate, reusable component. This change enhances code readability and promotes component reuse, adhering to best practices for React design patterns.
=> [BUG] Extract ContainerAvatar to a separate component

server/src/integrations/shell/managers/SshPrivateKeyFileManager.ts
The new version simplifies the creation of temporary SSH private key files. The previous explicit error checking code has been removed and replaced with a direct instruction to execute a shell command. This ensures a more concise and efficient execution flow.
=> Refactor SSH private key file creation

server/src/services/playbooks/galaxy.validator.ts
Simple regexp for Galaxy shell install to prevent unwanted sec issues
=> [CHORE] Sec no funny business

client/config/config.ts, server/src/modules/docker/utils/utils.ts
Updated the container removal utility with proper void statement for asynchronous operation compliance. Additionally, enabled granular code splitting in the client configuration to improve load performance.
=> [CHORE] Refactor container deletion and enable code splitting

client/package.json, server/package.json, shared-lib/package.json
This updates the version numbers in the shared-lib, server, and client package.json files. The new version, 0.1.17, ensures consistency across all parts of the SquirrelServersManager project.
=> [CHORE] Update package versions to 0.1.17

client/src/pages/Devices/components/ListComponent.tsx
Changed lazyLoad from "progressive" to "ondemand" to optimize performance. Added configurations for slidesToShow, slidesToScroll, infinite scrolling, and adaptiveHeight to enhance user experience.
=> [BUG] Update Carousel lazyLoad and behavior settings

client/src/app.tsx, client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/pages/Admin/Logs/index.tsx, client/src/pages/Admin/Settings/Settings.tsx, client/src/pages/Admin/Settings/components/Information.tsx, client/src/pages/Automations/Automations.tsx, client/src/pages/Devices/index.tsx, client/src/pages/Playbooks/components/DirectoryTreeView.tsx, client/src/pages/Services/index.tsx
Sync tabs with URL hash and add animations
Enhanced tab navigation across various pages by synchronizing active tabs with the URL hash, allowing for direct linking and improved state management. Introduced framer-motion animations in NewDeviceModal for a smoother user experience.
=> [CHORE] Chore small improvements

client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionDropDown.tsx, client/src/components/PlaybookExecutionModal/PlaybookExecutionTerminalModal.tsx, client/src/components/PlaybookSelection/PlaybookSelectionModal.tsx, client/src/pages/Admin/Settings/components/AdvancedSettings.tsx, client/src/pages/Admin/Settings/components/AuthenticationSettings.tsx, client/src/pages/Admin/Settings/components/GeneralSettings.tsx, client/src/pages/Admin/Settings/components/PlaybooksSettings.tsx, client/src/pages/Admin/Settings/components/RegistrySettings.tsx, client/src/pages/Playbooks/index.tsx
Updated multiple components to use responsive layout with Ant Design's Grid system. Consolidated repetitive layout code and enhanced UI consistency across the settings pages for better user experience on different screen sizes.
=> [CHORE] Refactor layout and improve responsiveness

client/src/components/LiveLogs/LiveLogs.tsx, client/src/pages/Devices/DeviceSSHTerminal.tsx, server/src/middlewares/Socket.ts, server/src/modules/ssh/SSHTerminalEngine.ts, server/src/modules/ssh/SSHTerminalInstance.ts, server/src/services/socket/container-logs.ts, shared-lib/src/index.ts, shared-lib/src/types/events.ts
Replaced hardcoded event names with SsmEvents enum across the project for consistency. Updated socket event handlers, emitters in server and client components, and added the new shared event types.
=> [CHORE] Standardize event names using SsmEvents enum

README.md, site/index.md
Removed "Coming soon" tag from the Collections feature in README and site index. Updated the embedded YouTube video link in the site index to a new URL for better content accessibility.
=> Update README and index for Collections feature availability

site/about.md, site/contribute/conventions.md, site/contribute/index.md, site/contribute/stack.md, site/docs/add-device.md, site/docs/add-unamanaged.md, site/docs/automations/automations.md, site/docs/delete-device.md, site/docs/device-configuration.md, site/docs/devmode.md, site/docs/docker.md, site/docs/exec-playbook.md, site/docs/first-time.md, site/docs/index.md, site/docs/manual-install-agent.md, site/docs/playbooks/local-playbooks.md, site/docs/playbooks/playbooks.md, site/docs/playbooks/remote-playbooks.md, site/docs/quickstart.md, site/docs/registry.md, site/docs/requirements.md, site/docs/services.md, site/docs/settings.md, site/docs/technical-guide.md, site/docs/troubleshoot.md, site/docs/userguide.md, site/index.md
After I saw some people on reddit complaining I decided to help out a bit. 
This pull request includes various updates and improvements to the documentation.
- Fixed typos and grammatical errors throughout
- Improved wording and clarity in multiple sections
- Updated formatting for consistency 
- Added missing information in some areas
- Removed redundant content
- Standardized capitalization and terminology (Title Case)
Key changes:
- Updated overview and feature descriptions on homepage
- Clarified installation and setup instructions
- Improved explanations of core concepts like playbooks and automations
- Added notes about security considerations
- Standardized formatting of code blocks and examples
=> Update documentation and fix typos

site/.vitepress/config.ts, site/useful-links.md
Created a new "useful-links.md" document with curated Ansible and Docker resources. Updated the navigation config to include a link to the new document under the "Useful links" section.
=> [DOC] Add useful links document and update site config

server-demo/src/data/ansible-conf.json, server-demo/src/routes/ansible.ts, server-demo/src/routes/index.ts
Implemented a new route in `ansible.ts` to return Ansible configuration details. Created and populated a JSON file `ansible-conf.json` with default Ansible settings.
=> [CHORE] Add endpoint for fetching Ansible configuration

client/src/components/Icons/CustomIcons.tsx, client/src/components/PlaybookExecutionModal/PlaybookExecutionTerminalModal.tsx, client/src/services/rest/ansible.ts, server/src/modules/ansible/SmartFailure.ts, server/src/routes/ansible.ts, server/src/services/rest/ansible/smart-failure.ts, server/src/services/rest/ansible/smart-failure.validator.ts, shared-lib/src/types/api.ts
Introduced the SmartFailure module to analyze Ansible logs and identify common failure patterns, providing probable causes and resolutions. Integrated SmartFailure detection into the REST service and client UI to notify users of potential issues and suggested fixes.
=> [FEAT] Add Ansible SmartFailure detection and handling

server/package-lock.json, server/package.json, server/src/data/database/model/AnsibleTask.ts, server/src/data/database/repository/ContainerRegistryRepo.ts, server/src/data/database/repository/DeviceAuthRepo.ts
Upgraded mongoose and mongodb dependencies for better performance and compatibility. Enhanced update operations in repository functions to be more specific about the query conditions, ensuring accuracy and consistency in data handling.
=> [CHORE] Update Mongoose and improve database operations

server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_retrieveAgentLogs.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/_upgrade.yml, server/src/tests/molecule/install-agent/converge.yml, server/src/tests/molecule/install-agent/destroy.yml, server/src/tests/molecule/install-agent/molecule.yml, server/src/tests/molecule/install-agent/prepare.yml, server/src/tests/molecule/install-agent/requirements.yml, server/src/tests/molecule/install-agent/verify.yml
Introduce new Molecule scenarios to test the install-agent playbook using Docker. These tests ensure the correct installation and configuration of necessary software components and validate the setup process with various checks and assertions.
=> [CHORE] Add Molecule tests for install-agent

site/index.md
Relocated the "Work in Progress" warning and YouTube video iframe to new positions within the index.md file. This restructuring aims to improve the layout and readability of the page without altering the content.
=> Move WIP warning and video iframe in index.md

client/src/components/PlaybookSelection/PlaybookSelectionModal.tsx, site/index.md
Replaced Select component with Dropdown.Button for better UI interaction in PlaybookSelectionModal. Added reset button in submitter and implemented menu click handler for mode change. Also, added a separator in the index.md file.
=> [CHORE] Enhance PlaybookSelectionModal with Dropdown button

site/.vitepress/config.ts, site/.vitepress/theme/index.js, site/apps/index.md, site/components/CardList.vue, site/package-lock.json, site/package.json
Created a new "Apps" section linked in the navigation and implemented a dynamic CardList component using Vuetify. Updated dependencies to include Vuetify and Axios for enhanced functionality and styling.
=> [DOC] Add Apps section and Vuetify support

.idea/vcs.xml, client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/pages/Containers/components/containers/InfoToolTipCard.tsx, client/src/pages/Playbooks/components/DirectoryTreeView.tsx, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_installAgent.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_reinstallAgent.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_updateAgent.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/roles/install_docker/tasks/install_docker.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/roles/start_agent_docker/tasks/main.yml, server/src/ansible/00000000-0000-0000-0000-000000000001/installers/install-docker.yml, server/src/controllers/rest/devices/device.validator.ts, server/src/modules/ansible/SmartFailure.ts
Adjust text width calculation in DirectoryTreeView for proper alignment. Add Docker dependency checks and improve Ansible tasks to include necessary package updates and better error handling. Adjust YAML schemas for better device validation and improved information display in UI components.
=> [CHORE][BUG]Refactor directory view, enhance Docker install

client/src/components/ComposeEditor/ViewBuilderElements/RenderFields.tsx, client/src/components/ComposeEditor/ViewBuilderElements/SmartFields.tsx, server/src/controllers/rest/containers/images.ts, server/src/controllers/rest/containers/networks.ts, server/src/controllers/rest/containers/volumes.ts
Removed default values for pagination parameters, conditionally paginated data only if parameters exist. Enhanced component naming and added new functionality for network and image selection in forms, using unique origin tags for better clarity.
=> [FEAT] Update query handling and improve form components

.github/workflows/molecule.yml, .idea/SSM.iml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/_ping.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/_reboot.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/_upgrade.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/docker/_createDockerNetwork.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/docker/_createDockerVolume.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/docker/_dockerCompose.yml, server/src/tests/molecule/README.md, server/src/tests/molecule/create-docker-network/prepare.yml, server/src/tests/molecule/default/molecule.yml, server/src/tests/molecule/default/run_all.yml, server/src/tests/molecule/install-docker/molecule.yml, server/src/tests/molecule/install-docker/playbook.yml, server/src/tests/molecule/install-docker/prepare.yml, server/src/tests/molecule/install-docker/tests/test_default.py, server/src/tests/molecule/requirements.txt
Added Molecule configuration files, test scenarios, and playbooks to facilitate Docker-related testing. Integrated these Molecule tests with a GitHub Actions workflow to ensure automated testing on push and pull request events. Also updated Ansible playbooks with comments and tags for better clarity.
=> [TESTS] Add Molecule tests and CI workflow integration

.github/workflows/molecule.yml, server/src/tests/molecule/default/molecule.yml
Enhanced `molecule.yml` with a comprehensive test sequence and added a debug step in GitHub Actions workflow for folder structure validation. These improvements aim to ensure consistency and ease troubleshooting during test runs.
=> Add test sequence and debug step in Molecule configurations

docker-compose.demo.dev.yml, docker-compose.demo.prod.yml, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.yml, server-demo/src/data/current-user.json, server-demo/src/data/custom-stacks.json, server-demo/src/data/dry-run.json, server-demo/src/routes/containers.ts
Introduced new JSON files for dry-run and custom stacks data, and added corresponding routes in containers.ts. Updated server version in current-user.json to 0.1.20. Removed version specification from various Docker Compose files.
=> [DOC] Add custom stacks data and routes, update server version

.gitignore, docker-compose.yml, site/.vitepress/config.ts, site/docs/containers/deploy-store.md, site/docs/requirements.md
Renamed the deploy doc to 'deploy-store' and updated its references. Added new environment variables to `docker-compose.yml` for better configuration. Enhanced the requirements documentation for clarity.
=> [DOC] Rename and update deploy docs, add env variables.

client/package-lock.json, client/package.json, server/package-lock.json, server/package.json, shared-lib/package-lock.json, shared-lib/package.json, site/package-lock.json, site/package.json
Updated various package versions and added missing license information to several dependencies in `package-lock.json`. These changes ensure all packages comply with licensing requirements and keep dependencies up-to-date.
=> [CHORE] Update dependencies and add missing licenses

README.md, getSSM.sh, server/src/ansible/00000000-0000-0000-0000-000000000000/device/_upgrade.yml, site/docs/quickstart.md, site/index.md
Updated the reboot condition in `_upgrade.yml` to limit reboots to CentOS/RHEL-based systems. Enhanced `getSSM.sh` by adding a welcome message, more detailed error messages with links, a port check for port 8000, and updated documentation for an easier and more guided installation process.
=> [CHORE][DOC] Refine upgrade trigger and enhance installation script

client/Dockerfile, client/src/pages/Playbooks/components/TreeComponent.tsx, docker-compose.dev.yml, server/Dockerfile, server/package-lock.json, server/src/helpers/ansible/AnsibleConfigurationHelper.ts, server/src/modules/playbooks-repository/default-repositories.ts, server/src/modules/shell/managers/AnsibleShellCommandsManager.ts, shared-lib/src/enums/settings.ts
Changed various paths to '/opt/squirrelserversmanager' for consistency and removed unnecessary 'dev' flags from dependencies in the package-lock.json files. This improves the structure and alignment of our project directory and dependencies.
=> [CHORE] Update file paths and remove redundant dev dependencies

server/src/controllers/rest/devices/device.ts, server/src/data/database/repository/ContainerRepo.ts, server/src/data/database/repository/ContainerStatsRepo.ts, server/src/modules/docker/core/WatcherEngine.ts, server/src/modules/docker/core/conf.ts, server/src/modules/docker/registries/providers/provider.conf.ts, server/src/services/DeviceUseCases.ts
Modularized registry and watcher configurations by introducing constants for registry and watcher types. Added functions to handle container operations based on devices and container deletion. Improved error message during device creation.
=> [BUG] Fix containers not being sync right after device add

client/src/pages/Dashboard/Components/CombinedPowerCard.tsx, client/src/pages/Devices/components/ListComponent.tsx, server/src/services/DeviceUseCases.ts, server/src/tests/integration-tests/test/controllers/rest/user.test.ts, server/src/tests/integration-tests/test/use-cases/DeviceUseCases.test.ts
Corrected a typo in totalCpu calculation and adjusted memory rounding in various components. Added integration tests for DeviceUseCases to ensure accurate overview statistics for devices.
=> [BUG] Fix CPU and memory calculations, integrate DeviceUseCases tests

client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/pages/Playbooks/components/CreateNewVarForm.tsx, client/src/pages/Playbooks/components/ExtraVarsViewEditor.tsx, server/src/controllers/rest/user/user.ts, shared-lib/src/types/api.ts
Added a new `masterNodeUrl` field to the user settings and updated the code to populate it. Refactored `ExtraVarsViewEditor` to move the row rendering logic into its own `ExtraVarRow` component, improving readability and maintainability.
=> [BUG/CHORE] Add masterNodeUrl and refactor ExtraVars components

site/docs/automations/automations.md, site/docs/install/install.md, site/docs/install/proxy-free.md
Introduce a new "Docker Volume Action" to the automation options, expanding the functionality available. Additionally, provide an alternative installation method guide without using Nginx, while clarifying its unofficial support status.
=> [DOC] Add Docker Volume Action and Proxy-Free Install Guide

client/src/app.tsx, client/src/components/DeviceConfiguration/AdvancedSwitch.tsx, client/src/components/HeaderComponents/AvatarDropdown.tsx, client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/pages/Admin/Inventory/index.tsx, client/src/pages/Admin/Logs/ServerLogsColums.tsx, client/src/pages/Containers/components/Images.tsx, client/src/pages/Containers/components/Networks.tsx, client/src/pages/Containers/components/Volumes.tsx, client/src/pages/Containers/components/containers/ContainerDetailsModal.tsx, client/src/pages/Devices/components/ListComponent.tsx, client/src/pages/User/FirstTime/CreateUserForm.tsx, client/src/pages/User/FirstTime/index.tsx
Refactored various components to enhance responsiveness, added new CreateUserForm component for user onboarding, and updated styles to better handle different screen sizes. Modified tables, modal dialogs, and various other UI elements to ensure better user experience across devices.
=> [CHORE] Try to improve responsiveness

client/package.json, server/package.json, shared-lib/package.json
Bump version numbers to 0.1.23 across client, shared-lib, and server package.json files. This update ensures consistency in versioning across all related components.
=> [CHORE] Update versions for client, shared-lib, and server

client/src/pages/Containers/components/containers/ContainerMetas.tsx
[Prevent incorrect URL if public port of container not available](https://github.com/SquirrelCorporation/SquirrelServersManager/commit/cb51101fc9e9d116f0a7697890a9464aec7da3c7)
=> [BUG] Prevent incorrect URL if public port of container not available

client/src/pages/Admin/Settings/components/ContainerStacksSettings.tsx, client/src/pages/Admin/Settings/components/PlaybooksSettings.tsx, shared-lib/src/types/api.ts
This commit removes redundant styling from popover components in ContainerStacksSettings and PlaybooksSettings. Additionally, it introduces new properties for enhanced error handling in the API types, adding `onError` and `onErrorMessage` fields to accommodate more robust error management.
=> [BUG] Remove unnecessary popover styling and extend error handling

client/src/components/Icons/CustomIcons.tsx, client/src/pages/Admin/Logs/TaskLogsTerminalModal.tsx, client/src/pages/Admin/Settings/components/ContainerStacksSettings.tsx, client/src/pages/Admin/Settings/components/PlaybooksSettings.tsx, client/src/pages/Admin/Settings/components/subcomponents/ContainerStacksGitRepositoryModal.tsx, client/src/pages/Admin/Settings/components/subcomponents/PlaybooksGitRepositoryModal.tsx, client/src/pages/Admin/Settings/components/subcomponents/PlaybooksLocalRepositoryModal.tsx, server/src/helpers/git/credential.ts, server/src/logger.ts, server/src/middlewares/ErrorHandler.ts, server/src/modules/automations/actions/AbstractActionComponent.ts, server/src/modules/automations/actions/DockerVolumeActionComponent.ts, server/src/modules/repository/git-playbooks-repository/GitPlaybooksRepositoryComponent.ts
Updated logging statements to include additional context for better traceability. Enhanced repository modals with improved actions such as confirmation prompts, button customizations, and navigation to logs. Removed unused logger imports and refined UI components for consistency.
=> [CHORE] Enhance logging and improve repository modals usability

client/package-lock.json, client/package.json, client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionDropDown.tsx, client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionReference.tsx, client/src/components/DeviceComponents/SFTPDrawer/Actions/DownloadModal.tsx, client/src/components/DeviceComponents/SFTPDrawer/Actions/MkdirModal.tsx, client/src/components/DeviceComponents/SFTPDrawer/Actions/RenameModal.tsx, client/src/components/DeviceComponents/SFTPDrawer/Actions/UpdateModeModal.tsx, client/src/components/DeviceComponents/SFTPDrawer/SFTPDrawer.tsx, client/src/components/DeviceComponents/SFTPDrawer/SFTPDropdownMenu.tsx, client/src/components/DeviceComponents/SFTPDrawer/utils.ts, client/src/components/Icons/CustomIcons.tsx, client/src/components/PlaybookSelection/PlaybookSelectionModal.tsx, client/src/pages/Admin/Settings/components/subcomponents/ContainerStacksGitRepositoryModal.tsx, client/src/pages/Admin/Settings/components/subcomponents/PlaybooksGitRepositoryModal.tsx, client/src/pages/Admin/Settings/components/subcomponents/RegistryModal.tsx, client/src/pages/Containers/components/containers/EditContainerNameModal.tsx, client/src/pages/Containers/components/sub-components/ContainerBackUpVolumeModal.tsx, client/src/pages/Playbooks/components/CreateFileInRepositoryModalForm.tsx, client/tests/components/DeviceComponents/SFTDrawer/utils.test.ts, server/package-lock.json, server/package.json, server/src/controllers/socket/sftp-session.ts, server/src/middlewares/Socket.ts, server/src/modules/ssh/SFTPEngine.ts, server/src/modules/ssh/SFTPInstance.ts, server/src/modules/ssh/socket-utils/file-stream.ts, shared-lib/src/types/api.ts, shared-lib/src/types/events.ts
Additionally, several dependencies, including AWS SDK packages, were updated to the latest versions.
=> [FEAT] SFTP module.

client/src/pages/User/Login/index.tsx, server/eslint.config.mjs, server/src/config.ts, server/src/controllers/rest/devices/devicestats.ts, server/src/data/statistics/DeviceMetricsService.ts, server/src/data/statistics/index.ts, server/src/services/DeviceStatsUseCases.ts, server/src/services/prometheus/PrometheusService.ts
Introduced `DeviceMetricsService` and `PrometheusService` for managing device metrics via Prometheus. Replaced manual metric registration and queries with centralized service methods. This enhances maintainability, scalability, and consistency across device statistics operations.
=> [CHORE] Refactor stats system to integrate Prometheus-based services

client/package-lock.json, client/package.json, server/package-lock.json, server/package.json
Updated various dependencies, including @vitest packages, framer-motion, and @rollup libraries, to their latest versions for improved performance and stability. These updates bring bug fixes, minor improvements, and compatibility enhancements.
=> [CHORE] Upgrade dependencies to latest versions.

.idea/vcs.xml, client/src/components/Charts/TinyRingProgressDeviceGraph.tsx, client/src/components/Charts/TinyRingProgressDeviceIndicator.tsx
Adjusted progress ring appearance and behavior with improved precision, dynamic styles, and better reactivity based on unique keys. Updated `.idea/vcs.xml` to include new project-specific Git mappings.
=> [CHORE] Refine TinyRing progress components and update VCS mappings

server/src/data/statistics/StatisticsRepo.ts, server/src/services/DashboardUseCase.ts
Updated memory and file storage usage calculations to use percentage-based metrics for better clarity and precision. Adjusted the logging for `available` memory and added a debug error log for dashboard metrics evaluation.
=> [CHORE] Refactor memory and storage usage calculations.

client/src/pages/Admin/Logs/ServerLogsColums.tsx, client/src/pages/Admin/Logs/index.tsx, server/src/data/database/model/Logs.ts, server/src/modules/remote-system-information/core/RemoteSystemInformationEngine.ts, server/src/modules/remote-system-information/helpers/queueProcessor.ts, server/src/modules/remote-system-information/watchers/RemoteSystemInformationWatcher.ts, server/src/tests/unit-tests/modules/remote-system-information/watchers/RemoteSystemInformationWatcher.test.ts, shared-lib/src/types/api.ts
Updated error logging to include complete error objects for better debugging. Enhanced Logs schema, API, and UI components to support display and handling of error details. Added additional methods to RemoteSystemInformationEngine for extended functionality.
=> [CHORE] Refactor error logging and enhance Logs schema/UI.

client/src/pages/Containers/components/containers/ContainerStatProgress.tsx, server/src/core/startup/index.ts, server/src/services/ContainerStatsUseCases.ts, server/src/services/DeviceStatsUseCases.ts, server/src/services/prometheus/PrometheusService.ts, server/src/services/prometheus/types/filters.ts, server/src/services/prometheus/types/prometheus.ts, server/src/tests/unit-tests/services/prometheus/PrometheusService.test.ts
Extracted Prometheus-related types into separate files for better modularity and maintainability. Refactored PrometheusService to simplify logic, enhance error handling, and improve metric querying, emphasizing consistency and type safety.
=> [CHORE] Refactor Prometheus service and add type definitions.

server/src/services/ContainerStatsUseCases.ts
Added error handling for both memory and CPU metric computations to prevent crashes when processing container stats. Warnings with relevant details are logged if an error occurs while setting metrics for a container.
=> [CHORE] Handle errors in container stats processing gracefully

client/src/components/DeviceConfiguration/ssh/HostCard.tsx, server/src/controllers/rest/devices/check-connection.ts, server/src/controllers/rest/devices/check-connection.validator.ts, server/src/controllers/rest/devices/device.validator.ts, server/src/helpers/dns/dns-helper.ts, server/src/modules/containers/core/CustomAgent.ts, server/src/modules/diagnostic/Diagnostic.ts, server/src/modules/remote-system-information/core/RemoteSSHExecutorComponent.ts, server/src/modules/ssh/SSHConnectionInstance.ts, server/src/services/DeviceUseCases.ts
Implemented hostname resolution logic using DNS for SSH connections. Updated validators to accept both IP addresses and hostnames. Modified UI and error messages to reflect this enhancement.
=> [FEATURE] Add support for hostnames alongside IP addresses in SSH

client/Dockerfile
Reverts SquirrelCorporation/SquirrelServersManager#906
=> Revert "Bump node from 23.11.0-alpine to 24.0.1-alpine in /client"

client/.dockerignore, client/Dockerfile, server/Dockerfile
Improved Dockerfile structure by introducing multi-stage builds for both client and server. Separate stages were added for shared-lib building, dependency installation, and production setup to minimize image size and enhance reusability. Updated `.dockerignore` to exclude unnecessary files, improving build efficiency.
=> [CHORE] Refactor Dockerfiles for optimized multi-stage builds.

server/Dockerfile
Reordered and deduplicated dependency installation steps for clarity and consistency. Moved shared package installations to appropriate build stages to streamline the build process. Improves maintainability and reduces redundancy in the Dockerfile.
=> [BUG] Refactor Dockerfile to reorganize dependency installation

client/src/pages/Dashboard/ChartComponents/ChartCard.less, client/src/pages/Dashboard/ChartComponents/MiniProgress.less, client/src/pages/Dashboard/ChartComponents/Trend.less
Replaced variable-based and inconsistent colors with a unified, hardcoded dark theme color palette. Adjustments improve readability, consistency, and visual design coherence across Trend, MiniProgress, and ChartCard components.
=> [CHORE] Update dashboard styles with refined color palette
