SquirrelCorporation/SquirrelServersManager

client/Dockerfile, server/Dockerfile, server/src/ansible/_installAgent.yml, server/src/ansible/_reinstallAgent.yml, server/src/ansible/_restartAgent.yml, server/src/ansible/_uninstallAgent.yml, site/.gitignore
Optimised agent scripts concerning install, uninstall, reinstall, and restart processes by using PM2 for agent management instead of shell scripts. Updated Dockerfiles for both client and server to install node packages with '--no-audit' flag. Additionally, '.gitignore' file has been updated to ignore 'package-lock.json'.
=> Refactor agent scripts and improve Dockerfiles

server/src/integrations/ansible/transformers/InventoryTransformer.ts, server/src/tests/integrations/ansible/InventoryTransformer.test.ts
Added two new integration tests in `InventoryTransformer.test.ts` for SSH key-based authentication scenario without and with key phrase. Updated inventory builder function inside `InventoryTransformer.ts` to cater for optional key phrase in key-based SSH authentication.
=> Add tests and update inventory builder for SSH key auth

server/src/integrations/docker/core/DockerAPIHelper.ts, server/src/tests/integrations/docker/Docker.test.ts, server/src/tests/integrations/docker/DockerAPIHelper.test.ts
Implemented comprehensive test scenarios for the DockerAPIHelper class in a new file. The testing includes cases for handling different SSH Types for both default and custom Docker SSH. In addition, cleaned up commented-out errors and added "cronstats" flag in "Docker.test.ts".
=> Add tests for DockerAPIHelper and update existing test files

server/src/core/startup/index.ts, server/src/integrations/shell/index.ts, server/src/tests/integrations/ansible/InventoryTransformer.test.ts, server/src/tests/integrations/docker/DockerAPIHelper.test.ts
The change primarily involves refining the import statements to streamline the code base. The refactor includes importing SettingsKeys in the startup module and SsmAnsible across multiple modules and changing the encryption logic method in DockerAPIHelper.test. Other changes include minor tweaks in the async/await functions and the removal of an unused import in the shell module.
=> Refactor import statements for SsmAnsible and SettingsKeys

client/package.json, server/package.json
The package dependencies for both the server and client side have been updated. The libraries "mongoose", "@aws-sdk/client-ecr", and "eslint" for the server, and "antd" and "eslint" for the client, have been updated to newer versions. These updates contain bug fixes and improvements which help keep our application secure and efficient.
=> Update package dependencies

server/src/helpers/PaginationHelper.ts, server/src/helpers/SorterHelper.ts, server/src/tests/helpers/FilterHelper.test.ts, server/src/tests/helpers/Pagination.test.ts, server/src/tests/helpers/SorterHelper.test.ts
This update includes comprehensive tests for `PaginationHelper`, `SorterHelper`, and `FilterHelper`. Additionally, error handling has been added to `SorterHelper` to deal with invalid JSON, and `PaginationHelper` has been tweaked to return an empty array if passed null or undefined data.
=> Add tests and enhancements for helper functions

server/src/integrations/ansible/utils/InventoryTransformer.ts
Added optional SSH port and user fields to the connection variables in InventoryTransformer. The fields will now be filled during the transformation process with provided SSH user and SSH port details.
=> Update InventoryTransformer to include SSH port

server/src/integrations/ansible/utils/ExtraVarsTransformer.ts, server/src/tests/integrations/ansible/ExtraVars.test.ts, server/src/tests/integrations/ansible/ExtraVarsTransformer.test.ts
In this commit, tests have been added for the ExtraVarsTransformer function to ensure proper functioning and error handling. The function now includes a try-catch block to manage potential errors during the transformation of extraVars. In addition, import statements in the ExtraVars.test.ts file have been rearranged.
=> Add tests and error handling for ExtraVarsTransformer

server/src/integrations/playbooks-repository/PlaybooksRepositoryComponent.ts, server/src/tests/integrations/playbooks-repository/PlaybookRepositoryComponent.test.ts, server/src/use-cases/PlaybooksRepositoryUseCases.ts
The code modifications focus on two key changes: refactoring the logging in the PlaybooksRepositoryComponent and amending the filesystem operation in PlaybooksRepositoryUseCases. The logger method now wraps the logging statement in a more efficient method call, and a directory creation operation has been replaced with a file deletion operation.
=> BUGFIX - Fix deletion following refacto

client/src/pages/Playbooks/components/DirectoryTreeView.tsx, client/src/pages/Playbooks/components/PlaybookDropdownMenu.tsx, client/src/pages/Playbooks/components/TreeComponent.tsx
Prevent user to delete a default directory or file;
Must be improved in the future by preventing any changes to the file structure of default repos
=> [BUG] Fix protected directory

server/src/core/startup/index.ts, server/src/data/database/model/Playbook.ts, server/src/data/database/repository/UserRepo.ts, server/src/services/user/user.ts, shared-lib/src/enums/settings.ts
Added an automatic default local user repository for playbooks when a new user is created. This was done by modifying startup logic to include a default user creation function, and updating the UserRepo to support this change. The SCHEME_VERSION in settings has also been updated to reflect the change.
=> [FEAT] Add default local repository for playbooks on user creation

server/src/integrations/shell/ShellWrapper.ts, server/src/services/playbooks/playbook.ts
The order of the arguments in the 'editPlaybook' function was switched to ensure proper functionality. The change was also reflected in the shell file 'ShellWrapper.ts' to maintain consistency across the application. The argument that was formerly named 'str' has been renamed to 'content' for better code readability.
=> [FIX] Fix incorrect argument order in editPlaybook function

client/src/pages/Devices/index.tsx
The lazyLoad setting for the Carousel component in the Devices page has been updated to 'progressive' from 'ondemand'. This change is intended to improve the loading behavior of the Carousel for a smoother user experience.
=> [BUG] Update Carousel lazyLoad setting to progressive

client/src/components/DeviceConfiguration/CheckDeviceConnection.tsx, client/src/components/TerminalModal/TerminalLogs.tsx, server/src/ansible/inventory/inventory.py
Changed the ansible inventory URL from '/ansible/inventory' to '/playbooks/inventory' for improved coherence with the path structure. Updated certain user interface messages to provide clearer instructions and function description. Also, modified terminal log processing to ensure indentation level doesn't go negative for better log readability.
=> Update ansible URL and refine UI messages

client/src/components/Template/Title.tsx, client/src/pages/Admin/Settings/components/AdvancedSettings.tsx, client/src/services/rest/settings.ts, server/src/routes/settings.ts, server/src/services/settings/advanced.ts
A new feature called "deletePlaybooksModelAndResync" has been added to the advanced settings. This allows users to delete all playbooks and then resync again. Modifications were made to server routing, client services, and the Advanced Settings UI component to accommodate this change.
=> Add feature to delete and resync playbooks

client/src/pages/Devices/ContainerMetas.tsx, client/src/pages/Devices/components/ListComponent.tsx, client/src/pages/Devices/index.tsx, client/src/pages/Services/components/EditContainerNameModal.tsx, client/src/pages/Services/index.tsx, server/src/services/containers/containers.ts
Moved ContainerMetas component to the 'Device' page directory. ContainerMetas has been given functionality to list containers specific to a device based on a provided device UUID. Likewise, routes are updated to link to this new device-specific container view. Other code cleanups and component restructures are also performed to improve maintainability.
=> [FEAT] Add ability to show containers for specific device

client/src/pages/Dashboard/Components/MainChartCard.tsx
The loading state in MainChartCard has been updated to reflect the latest data fetching status. The previous code used a hardcoded timeout to set loading to false which was removed. A loading spinner from Ant Design was added to provide a better visual feedback when fetching the data.
=> [CHORE] Update loading state in MainChartCard

client/src/pages/Admin/Inventory/index.tsx, server/src/modules/ansible/utils/ExtraVars.ts, shared-lib/src/types/api.ts
Updated the ExtraVars code to not throw an error when the ExtraVars value is not found and it's local. This update provides better handling of non-local errors and avoids unnecessary alerts for local ones. Additionally, updated the command reference in the terminal from '_installAgent' to 'installAgent' for improved readability.
=> [FIX] Refactor extra variable handling and command reference

shared-lib/src/enums/settings.ts
The SCHEME_VERSION in the DefaultValue enum has been updated from '7' to '8'. This change the version numbers to remain consistent with the overall project versioning scheme.
=> [CHORE] Update SCHEME_VERSION in DefaultValue enum

server/src/services/playbooks/galaxy.ts
Adjusted the offset calculation for the pagination system in the Ansible Galaxy service. This fix will ensure that the correct offset is used for retrieving specific sets of data from Ansible Galaxy API, improving the accuracy of fetched data.
=> [BUG] Fix offset calculation for Ansible Galaxy service

client/Dockerfile, server/Dockerfile
This commit changes the npm command in the server and client Dockerfiles from 'npm install' to 'npm ci' for more reliable, faster builds. This change affects both development and production environments and aims to improve the overall efficiency of the server and client build process.
=> [CHORE] Replace npm install with npm ci in Dockerfiles

server/src/modules/ansible/utils/InventoryTransformer.ts
Added a new field to the ConnectionVars interface - ansible_become_user, and set its value from the deviceAuth object. This allows setting a specific user for privilege escalation in Ansible.
=> [CHORE] Add become user field to ConnectionVars

docker-compose.yml
This change updates the docker-compose configuration to use a prebuilt image from GitHub Container Registry for the proxy service. This will streamline deployments by eliminating the need to build the proxy image locally, ensuring consistency across environments.
=> Switch proxy service to use prebuilt Docker image

client/src/pages/Services/components/StatusTag.tsx, server/src/data/database/repository/ContainerRepo.ts, server/src/modules/automations/actions/PlaybookActionComponent.ts, server/src/modules/docker/watchers/providers/docker/Docker.ts, shared-lib/src/enums/status.ts
Enhanced logging in PlaybookActionComponent to show retry attempts. Added functionality to update containers' status to 'UNREACHABLE' if Docker API fails, and included new enum value for this status. Updated UI to reflect the new 'UNREACHABLE' status with appropriate icon.
=> [CHORE] Update container status handling for unreachable state

client/Dockerfile, server/Dockerfile
Moved the COPY command after npm ci in both server and client Dockerfiles. This ensures that dependencies are installed before copying the application code, which can help leverage Docker layer caching more effectively during builds.
=> [CHORE] Reorder Dockerfile COPY commands for consistency

client/Dockerfile
Upgraded Node.js base image from version 22.4.1-alpine to 22.5.1-alpine. This update ensures the application benefits from the latest patches and improvements in the Node.js ecosystem. No other changes were made in this commit.
=> [CHORE] Update Node.js version in client Dockerfile

server/src/App.ts, server/src/middlewares/Socket.ts
Removed an outdated TypeScript comment in `Socket.ts` to clean up the code. Modified the `App.ts` to enforce the initialization of the `server` property, improving type safety and initialization clarity.
=> [BUG] Remove outdated comment and ensure server initialization

client/src/pages/Automations/components/Drawer/AutomationTriggerInnerCard.tsx
Ensure that the cron value is not redundantly reset if it is already set. Added conditional checks to compare existing cron values, preventing unnecessary state updates.
=> [BUG] Fix cron value synchronization in AutomationTriggerInnerCard

server/src/data/database/repository/AnsibleTaskRepo.ts
Modified the MongoDB `findOneAndUpdate` query in `updateStatus` function to enforce strict equality on the `ident` field. This ensures that the identification field comparison is precise, reducing potential mismatches.
=> [CHORE] Refactor updateStatus query to use strict equality.

client/src/pages/Automations/components/Drawer/AutomationTriggerInnerCard.tsx
Previously, cronValue was always initialized to '0 * * * *'. Now, it is set based on the formRef's current value if available, ensuring consistency with existing form data.
=> [BUG] Set initial cronValue from formRef

server/src/tests/unit-tests/modules/ansible/AnsibleCmd.test.ts
Include the ANSIBLE_CONFIG_FILE environment variable in the Ansible command execution tests. This ensures the tests validate the presence of the ansible configuration file in the command string, enhancing test accuracy.
=> [CHORE] Add ANSIBLE_CONFIG to AnsibleCmd test cases

client/src/components/NewDeviceModal/NewDeviceModal.tsx
Ensure default SSH connection uses PARAMIKO when not provided. Set strictHostChecking to true if not specified, improving default security settings.
=> [BUG][CHORE] Add default values for SSH connection and host checking

server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_restartAgent.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_retrieveAgentLogs.json, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_retrieveAgentLogs.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_uninstallAgent.json, server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_uninstallAgent.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/_upgrade.yml, server/src/modules/ansible/SmartFailure.ts, server/src/modules/ansible/extravars/ExtraVars.ts, shared-lib/src/enums/ansible.ts
Introduced a new context variable `_ssm_agentLogPath` for handling agent log paths across various Ansible playbooks. Updated the uninstall, retrieve logs, and restart tasks to manage agent logs more effectively, including conditional log path handling and cleanup. Enhanced error management and user feedback for Docker connection issues.
=> [BUG] Add support for agent log path management in Ansible tasks

server-demo/src/data/ansible-smart-failure.json, server-demo/src/data/playbooks.json, server-demo/src/routes/ansible.ts
Replaced 'canBeOverride' properties with 'type' in playbooks.json for better clarity and precision. Added new Ansible smart failure endpoint and created ansible-smart-failure.json to handle specific unreachable device scenarios.
=> Update playbooks.json and add Ansible smart failure endpoint

server/src/controllers/rest/devices/device.ts, server/src/services/DeviceUseCases.ts, shared-lib/src/enums/settings.ts
Replaced AnsibleReservedExtraVarsKeys with DefaultSharedExtraVarsList for master node URL. Updated imports and references accordingly in DeviceUseCases and device controller. Removed obsolete enum from settings.
=> [BUG] Refactor Ansible keys usage in cache settings

client/src/components/DeviceConfiguration/ssh/AuthenticationCard.tsx, server/src/controllers/rest/devices/check-connection.validator.ts, server/src/controllers/rest/devices/device.validator.ts, server/src/controllers/rest/devices/deviceauth.validator.ts, server/src/helpers/ssh/SSHCredentialsHelper.ts, server/src/modules/ansible/utils/InventoryTransformer.ts, server/src/tests/unit-tests/helpers/ssh/SSHCredentialsHelper.test.ts, server/src/tests/unit-tests/modules/ansible/InventoryTransformer.test.ts, shared-lib/src/enums/ansible.ts
I use tailscale to connect my nodes together because they exist on different networks. I'd still like to be able to use SSM to monitor and manage them. Since tailscale does not use a password, even regular SSH connection fail.
This change adds the ability to have an automatic (open to other names, if preferred) SSH connection that only needs a username. This is not supported by `paramiko`, so using automatic authentication requires the use of the built-in SSH connection type.
I've done my best to add tests and do manual testing with the dev docker-compose file. Please let me know if there are other tests needed or if there are any naming or architectural changes you'd prefer.
=> [FEAT] Add ability to use automatic SSH authentication

client/src/pages/Automations/components/Drawer/PlaybookActionSubForm.tsx, client/src/pages/Containers/components/Images.tsx, client/src/pages/Containers/components/Networks.tsx, client/src/pages/Containers/components/Volumes.tsx, client/src/pages/Containers/components/containers/ContainerMetas.tsx, client/src/pages/Containers/components/sub-components/CreateNetworkModal.tsx, client/src/pages/Containers/components/sub-components/CreateVolumeModal.tsx, client/src/pages/Containers/components/sub-components/DeployCustomStackModal.tsx, client/src/pages/Containers/components/sub-components/DeployModal.tsx, client/src/services/rest/device.ts, server/src/controllers/rest/devices/device.ts, server/src/routes/devices.ts
Added a new getAllDevices function in the server to fetch all devices and updated various client-side components to use this function instead of getDevices. This change ensures uniformity in device retrieval across the application.
=> [BUG] Add getAllDevices API endpoint and update client calls

client/src/components/ContainerComponents/ContainerQuickAction/ContainerQuickActionDropDown.tsx, client/src/components/ContainerComponents/ContainerQuickAction/ContainerQuickActionReference.tsx, client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionDropDown.tsx, client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionReference.tsx, client/src/pages/Automations/Automations.tsx, client/src/pages/Automations/components/AutomationQuickAction.tsx
Simplified the label structure of quick actions by adding a separate icon property. This enhances readability and maintainability by separating the icon and label elements.
Following Ant Design lib bump
=> [BUG] **Refactor quick action components to include icons**

client/src/pages/Containers/components/containers/ContainerMetas.tsx
Changed the URL path from '/manage/services/logs/' to '/manage/containers/logs/' in the ContainerMetas component. This ensures the log redirection points to the correct route for container logs.
=> [BUG] Update log path for container management

client/src/pages/Containers/components/containers/ContainerMetas.tsx, server/src/data/database/model/Container.ts, server/src/modules/docker/watchers/providers/docker/Docker.ts, shared-lib/src/types/api.ts
Enhanced the Docker module to parse and store container ports information. Updated the API types and database model to support ports. Modified the UI to display a link based on the container's public port.
=> [FEAT] Add container ports handling and display link in UI

client/src/components/DeviceConfiguration/ssh/AuthenticationCard.tsx, server/src/controllers/rest/devices/check-connection.validator.ts, server/src/controllers/rest/devices/device.validator.ts, server/src/controllers/rest/devices/deviceauth.validator.ts, server/src/helpers/ssh/SSHCredentialsHelper.ts, server/src/modules/ansible/utils/InventoryTransformer.ts, server/src/tests/unit-tests/helpers/ssh/SSHCredentialsHelper.test.ts, server/src/tests/unit-tests/modules/ansible/InventoryTransformer.test.ts, shared-lib/src/enums/ansible.ts
Updated the SSHType enumeration from "Automatic" to "PasswordLess" across controllers, validators, helpers, unit tests, and the client-side. This affects all references to ensure consistent handling of passwordless SSH authentication.
=> [CHORE] Rename SSHType.Automatic to SSHType.PasswordLess

.github/workflows/molecule.yml
Renamed the 'test' job to 'molecule-tests' for clarity. Updated the Molecule test execution to use 'working-directory' parameter for better readability and maintainability.
=> Rename job and refine Molecule test execution directory

client/package.json, client/src/app.tsx, client/src/components/DeviceConfiguration/CheckDeviceConnection.tsx, client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/components/NewDeviceModal/SwitchConnexionMethod.tsx, client/src/components/NoDevice/CarouselNoDevice.tsx, client/src/components/NoDevice/CarouselWithBlur.less, client/src/components/NoDevice/NoDeviceModal.tsx, server/package.json, server/src/core/startup/index.ts, server/src/data/database/model/Device.ts, shared-lib/package.json, shared-lib/src/enums/settings.ts, site/docs/quickstart.md, site/docs/technical-guide/manual-install-agent.md, site/docs/technical-guide/troubleshoot.md
Introduced a "No Device Modal" to provide an initial guide for users with no devices. Updated the technical guide with new sections for NodeJS Vanilla Agent, Dockerized Agent, and troubleshooting information. Adjusted various components for better Ansible playbook and Docker connection test handling.
=> [CHORE] Add no devices modal and update installation guides

.github/workflows/test-server.yml, server/package.json, server/src/ansible/requirements.txt, server/src/ansible/ssm-ansible-run.py, server/src/ansible/test_ssm_ansible_run.py
Add --vault-id ssm@ssm-ansible-vault-password-client.py to the command line arguments if 'cmdline' exists in runner_args. This ensures the vault ID is always passed for secure password management.
=> [BUGFIX] Append --vault-id to ansible runner command

server/src/ansible/00000000-0000-0000-0000-000000000000/device/_upgrade.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/roles/upgrade_host_package/debian.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/roles/upgrade_host_package/main.yml, server/src/ansible/00000000-0000-0000-0000-000000000000/device/roles/upgrade_host_package/rhel.yml, server/src/tests/molecule/default/run_all.yml, server/src/tests/molecule/upgrade-packages/Dockerfile.j2, server/src/tests/molecule/upgrade-packages/converge.yml, server/src/tests/molecule/upgrade-packages/molecule.yml, server/src/tests/molecule/upgrade-packages/requirements.yml, server/src/tests/molecule/upgrade-packages/verify.yml
Refactor the package upgrade logic by moving distribution-specific tasks to roles. Introduce Molecule tests to ensure proper functionality across Debian and RHEL-based systems. This enhances maintainability and improves test coverage.
=> [TEST] Refactor package upgrade logic and add Molecule tests

client/src/components/ComposeEditor/DockerComposeStackBuilder.tsx, client/src/components/ComposeEditor/StackPanel.tsx, client/src/pages/ComposeEditor/index.tsx
Renamed StackBuilder component to DockerComposeStackBuilder for better clarity. Added `onClickSaveStack` prop and enhanced stack icon rendering, improving UI consistency and code readability.
=> [BUG] Refactor StackBuilder to DockerComposeStackBuilder

.github/workflows/github-releases-to-discord.yml, site/docs/quickstart.md, site/index.md
Introduce a new GitHub Actions workflow to post release updates to Discord. Additionally, updated curl commands in documentation for better readability and simplicity.
=> [DOC] Add GitHub Actions workflow and update curl commands

server/package-lock.json, server/package.json, server/src/data/database/model/User.ts, server/src/middlewares/Passport.ts, server/src/tests/integration-tests/test/controllers/rest/login.test.ts, server/src/tests/integration-tests/test/controllers/rest/settings.test.ts, server/src/tests/integration-tests/test/controllers/rest/user.test.ts, server/src/tests/integration-tests/test/ping.test.ts, server/src/tests/integration-tests/vitest.config.mts, server/src/tests/integration-tests/vitest.setup.ts
This commit introduces integration tests for user-related controllers, including login, user creation, and settings management. It also adds the `passport-mock-strategy` package for testing environments and integrates it within the Passport configuration.
=> [TEST] Add integration tests and mock strategy for Passport

server/src/ansible/00000000-0000-0000-0000-000000000000/agent/roles/install_agent_node_v2/tasks/main.yml, server/src/tests/molecule/default/run_all.yml, server/src/tests/molecule/install-agent-enhanced/converge.yml, server/src/tests/molecule/install-agent-enhanced/destroy.yml, server/src/tests/molecule/install-agent-enhanced/molecule.yml, server/src/tests/molecule/install-agent-enhanced/prepare.yml, server/src/tests/molecule/install-agent-enhanced/requirements.yml, server/src/tests/molecule/install-agent-enhanced/verify.yml
Introduced a new Molecule scenario called 'install-agent-enhanced' with playbooks for preparation, convergence, and verification. Updated the main Molecule run file to include these tests, verifying Node.js, npm, PM2, and git installations as well as specific environment configurations.
=> [BUG] Add enhanced agent installation tests using Molecule

client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionDropDown.tsx, client/src/components/DeviceComponents/DeviceQuickAction/DeviceQuickActionReference.tsx
Introduced a needConfirmation flag in DeviceQuickActionReference to trigger confirmation prompts for critical actions like 'Reboot'. Integrated Popconfirm component in DeviceQuickActionDropDown to handle user confirmation before proceeding with these actions.
=> Add confirmation prompt for critical quick actions

server/src/ansible/default-ansible.cfg, server/src/core/startup/index.ts
Removed unnecessary imports from the project, including `SsmAnsible` and `UserRepo`, to streamline the codebase. Enabled the `profile_tasks` callback in the Ansible configuration to support performance profiling.
=> [CHORE] Remove unused imports and enable Ansible task profiling

server/__mocks__/fs.cjs, server/__mocks__/fs/promises.cjs, server/package-lock.json, server/package.json, server/src/tests/unit-tests/modules/shell/managers/SshPrivateKeyFileManager.test.ts
Implemented extensive unit tests for SshPrivateKeyFileManager using vitest and memfs for mocking file system operations. Updated project dependencies to include memfs in package-lock.json and package.json.
=> [CHORE] Add unit tests for SshPrivateKeyFileManager

server/src/ansible/00000000-0000-0000-0000-000000000000/device/_reboot.yml
Added 'become: true' to the Ansible playbook to ensure the reboot task runs with the necessary privileges. This change is required for successful execution of the device reboot.
=> [CHORE] Enable privilege escalation for device reboot task

README.md, client/src/components/NewDeviceModal/NewDeviceModal.tsx, server/src/controllers/rest/devices/check-connection.ts, shared-lib/src/types/api.ts
Added CheckAnsibleConnection and CheckDockerConnection types to api.ts and used these types in response objects for connection check responses. Updated README for better environment file instructions and fixed default URL initialization in NewDeviceModal.
=> [CHORE] Add type exports and fix response types for connection checks

client/src/app.tsx
Introduced a `fetchUserWithRetry` function to handle automatic retries when fetching user information fails. This refactoring replaces the previous direct calls to `hasUser` with a more robust approach, including retry and delay mechanisms.
=> [CHORE] Add retry logic to user fetching process

server/src/core/startup/index.ts
This commit introduces logic to generate and assign UUIDs to `ContainerVolume` entries that do not already have a UUID. This ensures each `ContainerVolume` entry has a unique identifier for better data integrity and tracking.
=> [CHORE] Add UUIDs to ContainerVolume entries missing them

client/src/components/Template/Title.tsx, client/src/pages/Admin/Settings/components/AuthenticationSettings.tsx, client/src/services/rest/settings.ts, server/src/controllers/rest/settings/keys.ts, server/src/controllers/rest/settings/keys.validator.ts, server/src/core/startup/index.ts, server/src/routes/settings.ts
This change modifies the startup process to check if '_ssm_masterNodeUrl' is already set in the cache before attempting to set it again. This prevents redundant operations and ensures the value is only set if it does not already exist.
=> [CHORE] Prevent duplicate cache setting for masterNodeUrl

client/src/pages/Admin/Settings/components/subcomponents/forms/DirectoryExclusionForm.tsx
Previously, the tags list did not include any default values. This update initializes the directoryExclusionList with common exclusion directories like 'production' and 'staging'. This helps ensure that these directories are excluded by default if no selections are made.
=> [CHORE] Set default directory exclusions for tags

.gitignore, client/package.json, server/package.json, server/src/controllers/rest/user/user.ts, server/src/core/startup/index.ts, shared-lib/package.json, shared-lib/src/enums/settings.ts
Updated version numbers across client, server, and shared-lib packages. Enhanced error handling in user creation and streamlined synchronous playbook registration process. Added `.idea/` to `.gitignore` for better development environment management.
=> [BUG] Update versions and improve error handling

server/src/helpers/ansible/AnsibleConfigurationHelper.ts
Renamed ANSIBLE_CONFIG_FILE to ANSIBLE_CONFIG_PATH and updated its usage. Added directory creation to ensure the configuration path exists before copying the ansible.cfg file.
=> [BUG] Refactor Ansible configuration path handling

client/src/pages/Dashboard/Components/MainChartCard.tsx, server/src/controllers/rest/devices/devicestatsdashboard.validator.ts, server/src/data/database/model/DeviceStat.ts, server/src/services/DeviceStatsUseCases.ts, shared-lib/src/enums/stats.ts, shared-lib/src/types/api.ts
This commit introduces the ability to track and display disk usage statistics, both used and free, in the Dashboard component. It updates the shared library, server, and client implementations to support numeric storage values to improve type safety and precision. Additionally, it
=> [FEAT] Add disk usage stats handling in Dashboard

client/src/pages/Admin/Inventory/components/AgentConfigurationTab.tsx, client/src/pages/Admin/Inventory/components/ConfigurationModal.tsx, client/src/pages/Admin/Inventory/index.tsx
Refactor device configuration component props
Renamed props from 'values' to 'device' for clarity and consistency across components. Removed unused icon imports and refactored the configuration modal to conditionally display tabs based on device status. This enhances code readability and maintains uniform naming conventions.
=> [BUG] Don't display the agent tab when the device is UNMANAGED

server/src/data/database/model/Device.ts
Changed the default cron schedule for dockerWatcherCron from hourly to every 4 hours. This ensures reduced frequency for better performance and resource optimization while maintaining functionality.
=> [CHORE] Update default cron interval for dockerWatcherCron

client/src/pages/ComposeEditor/index.tsx, server/src/helpers/docker/DockerComposeJSONTransformer.ts, server/src/tests/unit-tests/helpers/docker/transformToDockerCompose.test.ts
Renamed `lockUI` to `uiEditionDisabled` for clearer semantics in the UI. Enhanced DockerComposeJSONTransformer to support `service-volumes` and added `configs` field handling. Updated corresponding unit tests to reflect these changes.
=> [BUG] Refactor UI state and update Docker transformer logic

server/src/data/database/repository/ContainerCustomStackRepo.ts, server/src/data/database/repository/PlaybookRepo.ts, server/src/services/GitCustomStacksRepositoryUseCases.ts, server/src/services/PlaybooksRepositoryUseCases.ts
Updated repository deletion logic to use `deleteAllByRepository` instead of individual delete calls for both Playbook and CustomStack repositories. This change ensures bulk deletions are handled efficiently and consistently across related modules. Adjusted all relevant services and repositories to reflect the updated method.
=> [BUG] Refactor repository deletion to use deleteAllByRepository

client/src/pages/Admin/Settings/components/subcomponents/forms/GitForm.tsx, server/src/helpers/git/credential.ts, server/src/modules/repository/git-playbooks-repository/GitPlaybooksRepositoryComponent.ts, shared-lib/src/enums/git.ts
This commit introduces support for Gitea in credential handling and Git operations. It also enhances Git URL validation by adding rules for `https://` formatting and issuing warnings for insecure credentials in URLs. Additionally, it ensures repository errors are reset in various Git actions for better reliability.
=> [FEAT] Add Gitea support and improve Git URL validation.

.github/workflows/test-client.yml, .github/workflows/test-server.yml
This ensures that builds for both the server and client use the production environment, aligning with best practices and preventing unintended behavior during builds. Updated scripts in GitHub Actions workflows for test-server and test-client.
=> [CHORE] Set NODE_ENV to production for build steps in workflows

client/src/components/LiveLogs/LiveLogs.tsx, client/src/components/PlaybookExecutionModal/PlaybookExecutionTerminalModal.tsx, client/src/pages/Admin/Logs/TaskLogsColumns.tsx, client/src/pages/Admin/Logs/TaskLogsTerminalModal.tsx, client/src/pages/Admin/Logs/index.tsx, client/src/pages/Devices/DeviceSSHTerminal.tsx, client/src/services/rest/logs.ts, server/src/controllers/rest/logs/task.ts, server/src/controllers/rest/logs/task.validator.ts, server/src/routes/logs.ts
Introduced backend API for fetching task events and integrated it with a new TaskLogsTerminalModal component in the UI. Added rendering for logs with a terminal-like display and enhanced live logs with a stylized header. Also included validation for task event requests.
=> [CHORE] Add task event logs retrieval and display in the UI

server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_checkDeviceBeforeAdd.yml, server/src/controllers/rest/logs/task.ts, server/src/data/database/repository/AnsibleLogsRepo.ts
Improve `findAllByIdent` to allow sorting order customization. Update task logs controller to use ascending sort order. Extend Ansible playbook with sudo test and task completion debug output.
=> [CHORE] Add sorting option and enhance Ansible playbook tasks

client/package-lock.json, client/package.json, server/package-lock.json, server/package.json
Upgraded `antd` to v5.22.7, `rc-util` to v5.44.3, and `@aws-sdk/client-ecr` to v3.719.0 in both `package.json` and `package-lock.json`. This ensures compatibility with latest features, bug fixes, and security improvements.
=> [CHORE] Update dependencies: antd, rc-util, and @aws-sdk/client-ecr

server/src/tests/unit-tests/core/startup/Startup.test.ts
Introduces comprehensive tests for the `Startup` module to validate initialization behavior, including module initiation, scheme updates, Redis cache handling, and error logging. Mocks were implemented for external dependencies to ensure isolated and reliable test results.
=> [TEST] Add unit tests for `Startup` module initialization

.github/workflows/docker-publish.yml
This commit introduces a new job in the GitHub Actions workflow to build, tag, and publish the Prometheus Docker image. It includes setup for QEMU, Docker Buildx, and signing the image with cosign. The workflow also handles multi-platform builds and registry login for non-PR events.
=> Add Prometheus Docker image build-and-publish workflow

server/src/tests/unit-tests/helpers/vault-crypto/vault.test.ts, server/src/tests/unit-tests/modules/docker/Registry.test.ts, server/src/tests/unit-tests/modules/remote-system-information/system-information/bluetooth/bluetooth.utils.test.ts, server/src/tests/unit-tests/modules/remote-system-information/system-information/remoteos.utils.test.ts, server/src/tests/unit-tests/modules/remote-system-information/system-information/utils.test.ts, server/src/tests/unit-tests/modules/remote-system-information/watchers/RemoteSystemInformationWatcher.test.ts
Replaced synchronous `expect` statements with asynchronous `await expect` in several test files to improve consistency and correctness. Added new test cases for RemoteSystemInformationWatcher, Bluetooth utils, OS utils, and general utilities to ensure coverage of edge cases and input handling.
=> [CHORE] Refactor tests to use async methods consistently

client/src/pages/User/FirstTime/CreateUserForm.tsx
Replaced custom regex for email validation with Ant Design's `type: 'email'` rule. This simplifies code and improves maintainability while ensuring consistent validation behavior.
=> [BUG– Use Ant Design's built-in email validation

client/src/components/DeviceComponents/SFTPDrawer/Actions/DownloadModal.tsx, server/src/modules/ssh/SFTPInstance.ts
Updated the SFTP file handling logic to differentiate between files and directories. Added functionality to create and download tarballs for directories, ensuring efficient transfer. Improved error handling and logging for better debugging and user feedback during file operations.
=> [FEAT] Enhance SFTP file download to support directories as tarballs

server/src/tests/unit-tests/modules/remote-system-information/system-information/RemoteOS.test.ts, server/src/tests/unit-tests/modules/remote-system-information/system-information/system/system.utils.test.ts
Introduces comprehensive unit tests for `system.utils` methods, including `macOsChassisType`, `cleanDefaults`, `getAppleModel`, and `parseDateTime`. Additionally, adds tests for `RemoteOS` functionality such as OS detection, system information retrieval, file operations, platform-specific checks, and error handling. These tests enhance the reliability and maintainability of the codebase.
=> [CHORE] Add unit tests for system utilities and RemoteOS features

server/src/helpers/sudo/sudo.ts, server/src/modules/remote-system-information/core/RemoteSSHExecutorComponent.ts, server/src/modules/remote-system-information/system-information/types.d.ts
Replaced in-line privilege elevation logic with a more unified and dynamic approach using `generateSudoCommand`. Removed unnecessary `isElevated` tracking and redundant privilege elevation method to simplify the codebase. This ensures privilege escalation is handled directly when executing commands, improving maintainability and consistency.
=> [CHORE] Refactor SSH command execution to streamline privilege elevation

server/src/modules/remote-system-information/core/RemoteSSHExecutorComponent.ts
Added a call to `startKeepAlive` after establishing an SSH connection. This ensures the connection remains active by sending periodic keep-alive signals, reducing the risk of unintended disconnections.
=> [CHORE] Enable SSH keep-alive mechanism upon connection establishment

.github/dependabot.yml
This change introduces Dependabot configuration for Dockerfiles in the /prometheus directory. It ensures weekly checks for dependency updates, improving maintainability and security of the Docker setup.
=> [CHORE] Add Dependabot config for Docker updates in /prometheus

server/src/core/startup/index.ts, server/src/tests/unit-tests/core/startup/Startup.test.ts
Added logic to apply default playbook configurations for all devices during the startup process. This ensures consistent initialization of devices after synchronizing indexes.
=> [CHORE] Synchronize playbook defaults during device startup.

client/package.json, server-demo/src/data/current-user.json, server/package.json, server/src/core/startup/index.ts, shared-lib/package.json
Bumped project version from 0.1.26 to 0.1.28 across all modules. Removed the unused `DeviceStatRepo` import from the server startup code to clean up unused references. This ensures consistency and prepares the codebase for future updates.
=> [CHORE] Upgrade to version 0.1.28 and remove unused dependency.

server/src/tests/unit-tests/core/startup/Startup.test.ts
Updated the Startup tests to mock and verify the initialization of the RemoteSystemInformationEngine. This ensures proper coverage and validation for its integration within the startup process.
=> [CHORE] Add tests for RemoteSystemInformationEngine initialization

client/src/components/DeviceConfiguration/CheckDeviceConnection.tsx, client/src/components/DeviceConfiguration/diagnostic/ExistingDeviceConnectionTest.tsx, client/src/components/NewDeviceModal/NewDeviceModal.tsx, client/src/services/rest/device.ts, server/src/controllers/rest/devices/check-connection.ts, server/src/controllers/rest/devices/check-connection.validator.ts, server/src/modules/remote-system-information/core/RemoteSSHExecutorComponent.ts, server/src/routes/devices.ts, server/src/services/DeviceUseCases.ts, shared-lib/src/types/api.ts
Introduced functionality to validate Remote System Information connection during device setup and diagnostics. Updated client, server, and shared-lib components to integrate this feature, including API endpoints, UI adjustments, and backend logic for connection testing.
=> [CHORE] Add support for Remote System Information connection tests

client/src/components/DeviceConfiguration/DockerConfigurationFormElements.tsx, client/src/components/DeviceConfiguration/docker/DockerWatchCard.tsx, client/src/services/rest/device.ts, docker-compose.dev.yml, server/src/controllers/rest/devices/configuration.ts, server/src/data/database/model/Device.ts, server/src/modules/containers/core/WatcherEngine.ts, server/src/modules/containers/watchers/providers/docker/Docker.ts, server/src/services/DeviceUseCases.ts, shared-lib/src/types/api.ts
Introduce a new `dockerWatchAll` flag to enable watching all containers, including stopped ones. Updated server, client, and database schema to handle the new configuration, and modified UI components to allow toggling the feature in advanced settings. Additionally, adjusted default behavior in Docker runtime to reflect this change.
=> [BUG] Add support for "watch all containers" configuration

prometheus/Dockerfile, prometheus/entrypoint.sh
Ensure the Prometheus data directory has correct permissions and ownership. Adjusted the entrypoint script to run Prometheus as the `nobody` user for improved security. Updated the Dockerfile to simplify the user setup and maintain compatibility with the modified entrypoint script.
=> [BUG] Set up proper permissions and user context for Prometheus

client/package.json, server/package.json, shared-lib/package.json
Updated the version number in client, server, and shared-lib package.json files to 0.1.29. This ensures consistency across all components and prepares the packages for release. No other changes were made.
=> [CHORE] Bump version to 0.1.29 across all packages

client/src/pages/Admin/Settings/components/Information.tsx, client/src/services/rest/settings.ts, server/src/controllers/rest/settings/information.ts, server/src/data/cache/index.ts, server/src/data/statistics/server-stats.ts, server/src/helpers/redis/redis-info.ts, server/src/routes/settings.ts, shared-lib/src/types/api.ts
Introduce endpoints to fetch MongoDB, Redis, and Prometheus server stats, along with corresponding client-side integration. Implement data parsing helpers, API types, and admin settings page updates to display server statistics.
=> [FEAT] Add server stats endpoints and client integration

client/config/routes.ts
Introduced redirects for '/manage', '/stack', and '/admin' routes to ensure user-friendly navigation and default sub-path handling. This change enhances usability by directing users to specific sub-routes when accessing these base paths.
=> [BUG] Add route redirects for improved navigation

client/src/components/NewDeviceModal/NewDeviceModal.tsx
Defined a constant `MODAL_MIN_HEIGHT` and applied it across multiple modal elements to ensure uniformity and better visual consistency, especially on smaller screens. This improves usability and layout stability for the modal content.
=> [CHORE] Set a minimum height for NewDeviceModal components

proxy/default.conf
Hi,
I am creating a ansible-role to add SSM to the [MASH-Playbook](https://github.com/mother-of-all-self-hosting/mash-playbook). 
The role should run the container in read-only mode. It is necessary to change `error_log off` to `error_log /dev/null` to prevent nginx from trying to create the file `/etc/nginx/off` (See: https://ahmetkun.com/post/etc-nginx-off-what-might-that-be/).
I'm looking forward to finally use SSM and share the role with you, after I finished it.
=> fix(proxy): change to `error_log /dev/null`

client/src/components/DeviceComponents/DeviceInformation/components/CPUTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/FilesystemsTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/GraphicsTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/MemoryTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/NetworkInterfacesTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/OSTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/SystemInformationView.tsx, client/src/components/DeviceComponents/DeviceInformation/components/SystemTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/USBTab.tsx, client/src/components/DeviceComponents/DeviceInformation/components/WifiTab.tsx, client/src/pages/Admin/Inventory/components/tabs/SystemInformationConfigurationTab.tsx, server/src/modules/devices/domain/entities/device.entity.ts, server/src/modules/remote-system-information/infrastructure/queue/remote-system-information.processor.ts, shared-lib/src/namespace/system-information.ts, shared-lib/src/types/api.ts
- Included `lastUpdatedAt` prop in CPUTab, FilesystemsTab, GraphicsTab, MemoryTab, NetworkInterfacesTab, OSTab, SystemTab, USBTab, and WifiTab components to display the last update time for each system information section.
- Updated SystemInformationView to render a tooltip with the last updated timestamp.
- Enhanced the device entity and system information types to support last updated timestamps for various components.
=> [CHORE] Add last updated timestamps to system information tabs

client/src/components/Terminal/RemoteSystemInformationTerminal.tsx, server/src/modules/remote-system-information/application/services/components/watchers/remote-system-information-watcher.ts
Extended the watcher to handle `cpustats`, `memstats`, and `filesystemstats` components. Updated the terminal UI to include options for monitoring these new stats. This enhances system debugging and provides more comprehensive system monitoring capabilities.
=> [CHORE] Add support for CPU, Memory, and File System stats monitoring.

client/src/components/DeviceComponents/DeviceInformation/components/FilesystemsTab.tsx
Adjusted the logic for accessing `lastUpdatedAt` to use a fallback index of 0 when `selectedInterface` is undefined. This ensures safer handling of optional chaining and prevents possible runtime errors.
=> [BUG] Fix potential null coalescing issue in FilesystemsTab

client/src/components/NoDevice/NoDeviceModal.tsx
Update logic in NoDeviceModal to navigate users to the Manage Devices page when no device is available. This improves user experience by providing a clear path for device management.
=> [CHORE] Redirect to Manage Devices page if no device is available

server/src/modules/users/presentation/controllers/users.controller.ts
Since there is no https support out of the box, putting back the option for the cookie for HTTP support
=> [BUG] Set cookie 'secure' flag to false

client/src/pages/Admin/Inventory/components/tabs/SystemInformationConfigurationTab.tsx, server/src/modules/remote-system-information/infrastructure/queue/remote-system-information.processor.ts
- Correctly update `lastUpdatedAt` timestamps for CPU, memory, and file system stats.
- Ensure `devicesService.update` is consistently called to persist changes.
=> Fix device.systemInformation stats update logic in processor
